name: Run Property Scraper and App

on:
  schedule:
    - cron: '53 20 * * *'  # Runs every day at 6 AM UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  run-property-pipeline:
    runs-on: windows-latest  # or ubuntu-latest if you prefer Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run 1_property_urls.py
        run: python property-1/1_property_urls.py

      - name: Run add_tosnowflake.py
        run: python property-1/add_tosnowflake.py

      - name: Run Streamlit app (optional, headless)
        run: streamlit run property-1/app.py &
        shell: bash
